namespace InterfacePerfTest.SourceCodeBuilders
{
    internal interface IContainerSourceCodeBuilder
    {
        /// <summary>
        /// Generates source code which calls all the methods in the class generated by GetContainerSourceText.
        /// </summary>
        /// <returns>The source code string</returns>
        string GetCallingCodeSourceText();

        /// <summary>
        /// Generates source code for a container class.
        /// </summary>
        /// <returns>The source code string</returns>
        string GetContainerSourceText();
    }
}